import { HotspotType } from "@/types";
import { 
  Monitor, 
  Wifi, 
  Fingerprint, 
  Lock, 
  ShieldCheck, 
  KeyRound, 
  Smartphone, 
  Users, 
  BatteryCharging,
  Video,
  Expand,
  Moon,
  Server,
  Bot,
  HardDrive,
  Layers,
  List,
  Droplet,
  Radar,
  Volume2,
  Lightbulb,
  Scan,
  CloudRain,
  MoonStar
} from 'lucide-react';


export const entranceHotspots: HotspotType[] = [
  {
    id: "1",
    x: 63.4,
    y: 38.7,
    title: "Video Door Phone",
    description: "This smart video door phone provides high-resolution video and two-way communication, ensuring secure and convenient visitor management. Its sleek design and advanced features make it ideal for modern homes.",
    image: "https://images.ctfassets.net/m3x6aw9x53qp/2jo4LN0GrmiafAqkrS4lgt/9f477c436ac0015a82f23289a48c67bb/Qubo_Door_phone.webp",
    mediaType: "image",
    redirectUrl: "https://www.flipkart.com/redmi-watch-move-1-85-premium-amoled-14-day-battery-best-accuracy-dual-core-processor-smartwatch/p/itm3f270f4a5747a?pid=VIPHYXQG8FPKS8GK&lid=LSTVIPHYXQG8FPKS8GK27ROPB&marketplace=FLIPKART&cmpid=shameta2025",
    imageClassName: "w-auto h-40 xl:h-46 translate-y-3 -translate-x-5",
    cardPosition: 'left',
    cardOffsetY: 40,
    brand: "/qubo-logo.webp",
    brandClass: "h-auto w-14 sm:w-18  lg:-translate-y-0.25 xl:translate-y-1",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Video Door Phone",
    featuresWithIcons: [
      { text: "2K resolution camera", icon: Video },
      { text: "140° wide-angle lens", icon: Expand },
      { text: "Night vision", icon: Moon },
      { text: "Mobile app integration", icon: Smartphone },
      { text: "Motion and person detection", icon: Radar },
      { text: "Two-way audio with echo cancellation", icon: Volume2 },
      { text: "Dual-band Wi-Fi and Ethernet PoE support", icon: Server },
      { text: "Smart assistant compatibility", icon: Bot },
      { text: "Expandable storage up to 1TB", icon: HardDrive },
    ],
    buttonText: "Buy Now",
    hasMagnifier: true,
    magnifierZoom: 0.7,
    magnifierRadius: 70,
    magnifierImage: "/magnify/video-doorbell.webp",
    magnifierImageWidth: 600,
    magnifierImageHeight: 600,
    magnifierFocusX: 46,
    magnifierFocusY: 52,
  },
  {
    id: "2",
    x: 68.2,
    y: 40.3,
    title: "Smart Door Lock",
    description: "Designed for modern homes, the Atomberg SL1 combines advanced security with sleek design. With six unlocking methods, robust 5 stainless steel bolts, and free professional installation, it ensures both convenience and peace of mind.",
    image: "https://images.ctfassets.net/m3x6aw9x53qp/lKQ6knBnjJiH1hSk9PA5M/ecdac03b8eb88957b9ae497749c7210f/smart-door-lock.webp",
    mediaType: "image",
    mediaBackgroundColor: "bg-transparent lg:bg-black",
    redirectUrl: "https://www.flipkart.com/redmi-watch-move-1-85-premium-amoled-14-day-battery-best-accuracy-dual-core-processor-smartwatch/p/itm3f270f4a5747a?pid=SLOGTBZ36YXCVHPM&lid=LSTSLOGTBZ36YXCVHPMKFHYJT&marketplace=FLIPKART&cmpid=shameta2025",
    imageClassName: "w-auto h-48 lg:h-44 xl:h-56 ",
    cardPosition: 'left',
    tooltipPosition: "bottom",
    cardOffsetY: 36,
    brand: "/atomberg-logo.webp",
    brandClass: "h-auto w-14 sm:w-20 translate-y-0.75 xl:translate-y-1.5",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Smart Door Lock",
    featuresWithIcons: [
      { text: "Fast Fingerprint Access", icon: Fingerprint },
      { text: "Real-Time Access Logs", icon: List },
      { text: "6-in-1 Smart Unlock Options", icon: Layers },
      { text: "5 Stainless Steel Locking Bolts", icon: ShieldCheck },
      { text: "Anti-Peep Secure PIN Entry", icon: KeyRound },
      { text: "Manual Deadbolt Privacy Lock", icon: Lock },
      { text: "App Control via Bluetooth", icon: Smartphone },
      { text: "100 Fingerprints & NFC Cards", icon: Users },
      { text: "8-Month Battery with Backup", icon: BatteryCharging },
      { text: "IPX5 Water Resistance & Warranty", icon: Droplet },
    ],
    buttonText: "Buy Now",
    hasMagnifier: true,
    magnifierZoom: 0.75,
    magnifierRadius: 70,
    magnifierImage: "/magnify/atomberg.webp",
    magnifierImageWidth: 450,
    magnifierImageHeight: 450,
    magnifierFocusX: 48,
    magnifierFocusY: 52,
  },
  {
    id: "3",
    x: 80,
    y: 24,
    title: "Outdoor Camera",
    description: "This weatherproof outdoor camera combines high-resolution video with smart AI features, ensuring reliable surveillance in all conditions. Its robust design and intelligent detection capabilities make it ideal for safeguarding your property.",
    image: "https://images.ctfassets.net/m3x6aw9x53qp/316VrAONe8k9J1gyOscLNZ/b7b480eca210bc8bd258e1e8c3c020aa/Outdoor_cab.webp",
    mediaType: "image",
    mediaBackgroundColor: "bg-transparent",
    redirectUrl: "https://www.flipkart.com/redmi-watch-move-1-85-premium-amoled-14-day-battery-best-accuracy-dual-core-processor-smartwatch/p/itm3f270f4a5747a?pid=HSAGSREGRFVFADJX&lid=LSTHSAGSREGRFVFADJXLHHWIG&marketplace=FLIPKART&cmpid=shameta2025",
    imageClassName: "w-auto h-92 xl:h-106 translate-y-14 lg:translate-y-16",
    cardPosition: 'left',
    cardOffsetY: 170,
    brand: "/qubo-logo.webp",
    brandClass: "h-auto w-14 sm:w-18 translate-y-0.5 lg:translate-y-0.25 xl:translate-y-0.75",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Outdoor Camera",
    featuresWithIcons: [
      { text: "3MP (1296p) resolution", icon: Monitor },
      { text: "130° wide-angle lens", icon: Expand },
      { text: "Color night vision", icon: MoonStar },
      { text: "IP66 weather resistance", icon: CloudRain },
      { text: "AI-powered person detection", icon: Scan },
      { text: "Wi-Fi (2.4GHz) connectivity", icon: Wifi  },
      { text: "Smart spotlight with multiple modes", icon: Lightbulb },
      { text: "Two-way audio with echo cancellation", icon: Volume2 },
      { text: "Mobile app control with OTA updates", icon: Smartphone },
      { text: "Up to 1TB microSD and cloud storage support", icon: HardDrive }
    ],
    buttonText: "Buy Now",

    hasLightBeam: true,
    beamAngle: 145, 
    beamLength: 900,
    beamWidth: 60,
    beamColor: '#ffffff', 
    beamSpread: 800,
    beamOpacity: 0.1,
    beamGlowIntensity: 3,
    hasMagnifier: true,
    magnifierZoom: 0.8,
    magnifierRadius: 60,
    magnifierImage: "/magnify/outdoor-cam.webp",
    magnifierImageWidth: 700,
    magnifierImageHeight: 700,
    magnifierFocusX: 50,
    magnifierFocusY: 52,
  },
];
