import { HotspotType } from "@/types";
import { 
  Wifi,  
  Eye, 
  Moon, 
  Palette,
  Grid,
  Music,
  Scissors,
  Sun,
  Hourglass,
  Video,
  Rotate3D,
  Smartphone,
  Cloud,
  LayoutDashboard,
  ShieldCheck,
  Zap,
  Mic,
  Volume2, 
} from 'lucide-react';



export const kitchenHotspots: HotspotType[] = [
  {
    id: "1",
    x: 23,
    y: 60,
    title: "Strip Light",
    description: "This smart LED strip offers vibrant, customizable lighting with flexible installation and intuitive app control. Its multicolor effects and smart assistant compatibility make it ideal for enhancing ambiance in any space.",
    image: "https://images.ctfassets.net/m3x6aw9x53qp/4dTfm7O291u6wqv7xINl2c/72ef4aa0e8152acbb13142b56eafb5d7/Tapo_Strip_Lights.webp",
    mediaType: "image",
    redirectUrl: "https://www.flipkart.com/redmi-watch-move-1-85-premium-amoled-14-day-battery-best-accuracy-dual-core-processor-smartwatch/p/itm3f270f4a5747a?pid=LLSGRB6DGEY35HJG&lid=LSTLLSGRB6DGEY35HJG4UQ7ZT&marketplace=FLIPKART&cmpid=shameta2025",
    imageClassName: "w-auto h-40 xl:h-48 absolute top-0",
    cardPosition: 'right',
    brand: "/tapo-logo.webp",
    brandClass: "h-auto w-9 sm:w-12 absolute right-4 -translate-y-2.5 lg:-translate-y-2.75 xl:-translate-y-2",
    brandLogoWidth: 200,
    brandLogoHeight: 48, 
    productName: "Strip Light",
    featuresWithIcons: [
      { text: "16 million colors", icon: Palette },
      { text: "Music sync", icon: Music },
      { text: "2100 mcd brightness", icon: Sun },
      { text: "50 separate color zones", icon: Grid },
      { text: "Cuttable and flexible with 3M adhesive", icon: Scissors },
      { text: "Up to 50,000 hours lifespan", icon: Hourglass },
      { text: "PU coating for durability", icon: ShieldCheck  },
      { text: "No hub required", icon: Zap  },
      { text: "Voice control via Alexa, Google Assistant, and Siri Shortcuts", icon: Mic },
    ],
    cardOffsetY: -120,
    buttonText: "Buy Now",
    hasMagnifier: false,
    magnifierZoom: 1,
    magnifierRadius: 50,
  },
  {
    id: "2",
    x: 67.3,
    y: 2.2,
     title: "Indoor Camera",
    description: "This smart 3MP Wi-Fi camera keeps your home secure with clear footage, motion detection, and auto-tracking. AI alerts you to unusual activity, and cloud storage lets you review recordings anytime.",
    image:"https://videos.ctfassets.net/m3x6aw9x53qp/5UJ1I4PX2M0AjyleczmkNm/f39b246a32625675a9bf64b8a5bf4760/Qubo_Indoor_Camera.webm",
    mediaType: "video",
    mediaBackgroundColor: 'bg-transparent',
    redirectUrl: "https://www.flipkart.com/redmi-watch-move-1-85-premium-amoled-14-day-battery-best-accuracy-dual-core-processor-smartwatch/p/itm3f270f4a5747a?pid=HSAGZ85BFFSNHZ2Z&lid=LSTHSAGZ85BFFSNHZ2ZN01CZ3&marketplace=FLIPKART&cmpid=shameta2025",
    imageClassName: "w-auto h-48 sm:h-48 lg:h-44 xl:h-52 absolute ",
    cardPosition: 'bottom',
    tooltipPosition: "bottom",
    brand: "/qubo-logo.webp",
    brandClass: "h-auto w-12 sm:w-14 xl:w-16 absolute right-4 translate-y-0.5 lg:translate-y-0.75 xl:translate-y-1",
    brandLogoWidth: 200,
    brandLogoHeight: 48, 
    productName: "Indoor Security Camera",
    featuresWithIcons: [
      { text: "3MP full HD video clarity", icon: Video },
      { text: "2.4GHz Wi-Fi connectivity", icon: Wifi },
      { text: "360° pan & 85° tilt coverage", icon: Rotate3D },
      { text: "Two-way audio for instant communication", icon: Volume2 },
      { text: "Infrared night vision for dark environments", icon: Moon },
      { text: "Motion detection with smart alerts", icon: Eye },
      { text: "App control for live view & playback", icon: Smartphone },
      { text: "Supports local and cloud storage", icon: Cloud },
      { text: "Voice assistant compatibility (Alexa/Google)", icon: Mic },
      { text: "Compact design ideal for kitchen corners", icon: LayoutDashboard },
    ],
    buttonText: "Buy Now",
    hasLightBeam: true,
    beamAngle: 120, 
    beamLength: 800,
    beamWidth: 60,
    beamColor: '#ffffff', 
    beamSpread: 700,
    beamOpacity: 0.15,
    beamGlowIntensity: 3,
    hasMagnifier: true,
    magnifierZoom: 1.4,
    magnifierRadius: 50,
    magnifierImage: "/magnify/kitchen-indoorcam.webp",
    magnifierImageWidth: 200,
    magnifierImageHeight: 200,
    magnifierFocusX: 55,
    magnifierFocusY: 45,
    
  },
];
