import { HotspotType } from "@/components/hotspot";
import type { LucideIcon } from 'lucide-react';
import { 
  Monitor, 
  Mic, 
  Wifi, 
  Lightbulb, 
  Smartphone,  
  Moon, 
  Volume2, 
  Sun,
  SlidersHorizontal,
  CalendarClock,
  Bot,
  Hand,
  Layers,
  Leaf,
  Film,
  ShieldCheck,
  Users2,
  Radar,
  Rotate3D,
  Zap,
  HardDrive
} from 'lucide-react';

export interface HotspotTypeWithIcons extends HotspotType {
  featuresWithIcons?: Array<{
    text: string;
    icon?: LucideIcon;
    isFullWidth?: boolean;
  }>;
  imageWidth?: number | string;
  imageHeight?: number | string;
  imageClassName?: string;
}

export const livingroomHotspots: HotspotTypeWithIcons[] = [
  {
    id: "1",
    x: 22,
    y: 42,
    title: "Smart Light",
    description: "This smart LED bulb offers vibrant lighting with customizable colors and remote control, enhancing your home's ambiance and convenience. Its energy-efficient design and smart features make it a perfect addition to modern living spaces.",
    image: "https://videos.ctfassets.net/m3x6aw9x53qp/6PlJVoLJZenuSQqIeVSxcD/a54438c6cad3b885a97c86250b5e56ee/Philip_Smart_Light.webm",
    mediaType: "video",
    imageClassName: "w-auto h-44 xl:h-52 ",
    cardPosition: 'right',
    brand: "/philips-logo.webp",
    brandClass: "h-auto w-14 sm:w-16 translate-y-1 xl:translate-y-2",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Smart Light",
    featuresWithIcons: [
        { text: "16 million color options", icon: Lightbulb },
        { text: "Tunable white light (2700K–6500K)", icon: Sun },
        { text: "Dimmable brightness (10%–100%)", icon: SlidersHorizontal },
        { text: "Voice control via Alexa and Google Assistant", icon: Bot },
        { text: "Remote access through mobile app", icon: Smartphone },
        { text: "Customizable scheduling and timers", icon: CalendarClock },
        { text: "Group control for multiple bulbs", icon: Users2  },
        { text: "No hub required; operates over Wi-Fi", icon: Wifi },
    ],
    buttonText: "Buy Now",
    redirectUrl: "https://www.flipkart.com/philips-wi-fi-led-wiz-connected-b22-10-watt-smart-bulb/p/itmf57e60256574d?pid=LLSFVZZ3BSCRHFGJ&lid=LSTLLSFVZZ3BSCRHFGJNDTCBG&marketplace=FLIPKART&q=Smart+light+philips&store=igc%2Fb4q&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=de645a28-6793-443c-99e4-25ba34853693.LLSFVZZ3BSCRHFGJ.SEARCH&ppt=sp&ppn=sp&ssid=fer61ieqqo0000001747997685247&qH=92eb773793cc9ac7",
    hasMagnifier: true,
    magnifierZoom: 0.7,
    magnifierRadius: 80,
    magnifierImage: "/magnify/light.webp",
    magnifierImageWidth: 700,
    magnifierImageHeight: 700,
    magnifierFocusX: 52,
    magnifierFocusY: 40,
  },
  {
    id: "2",
    x: 51.2,
    y: 5.2,
    title: "Indoor Camera",
    description: "This compact indoor camera offers crystal-clear Full HD video and full-room coverage with 360° rotation. It's ideal for home or office security with smart features packed into a sleek design.",
    image:"https://images.ctfassets.net/m3x6aw9x53qp/4mYi3srQTg0hGrXL94gCss/48b6c76a4db3ed61d0d1882203007fd2/Tapo_indoor.webp",
    mediaType: "image",
    redirectUrl: "https://www.flipkart.com/tp-link-tapo-c210-1296p-3mp-pan-tilt-home-wi-fi-smart-security-camera/p/itmfee4c93365099?pid=HSAGCFREHPZZZQRY&lid=LSTHSAGCFREHPZZZQRYRX4PZB&marketplace=FLIPKART&q=tp+link+camera&store=igc%2Fj69%2Fagd&spotlightTagId=default_BestsellerId_igc%2Fj69%2Fagd&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps&fm=search-autosuggest&iid=997885da-af9d-41b8-8778-c31b2008a7a6.HSAGCFREHPZZZQRY.SEARCH&ppt=sp&ppn=sp&ssid=s1dhrez2800000001747997505231&qH=5bdcdd5ed7ef2337",
    imageClassName: "w-auto h-42 xl:h-48 ",
    cardPosition: 'bottom',
    tooltipPosition: "bottom",
    brand: "/tapo-logo.webp",
    brandClass: "h-auto w-12 absolute right-4 -translate-y-3.5 lg:-translate-y-3 xl:-translate-y-2.25",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Indoor Camera",
    featuresWithIcons: [
      { text: "Night vision", icon: Moon },
      { text: "MicroSD card support", icon: HardDrive  },
      { text: "Mobile app control", icon: Smartphone },
      { text: "Full HD 1080p resolution", icon: Monitor },
      { text: "Two-way audio", icon: Volume2  },
      { text: "360° pan and tilt", icon: Rotate3D },
      { text: "Wi-Fi and Ethernet support", icon: Wifi },
      { text: "Voice assistant compatible", icon: Bot },
      { text: "Motion and human detection", icon: Radar  },
    ],
    hasLightBeam: true,
    beamAngle: 50, 
    beamLength: 900,
    beamWidth: 60,
    beamColor: '#ffffff', 
    beamSpread: 900,
    beamOpacity: 0.1,
    beamGlowIntensity: 2,
    buttonText: "Buy Now",
    hasMagnifier: true,
    magnifierZoom: 0.75,
    magnifierRadius: 50,
    magnifierImage: "/magnify/tapo-indoorcam.webp",
    magnifierImageWidth: 450,
    magnifierImageHeight: 450,
    magnifierFocusX: 51,
    magnifierFocusY: 50,
  },
  {
    id: "3",
    x: 93.5,
    y: 56,
    title: "Baby Camera",
    description: "Keep your baby safe and comfortable with this smart Wi-Fi PT camera. It offers sharp 3MP video, 360° panoramic view, and 85° tilt to cover every corner - minimizing blind spots and keeping you connected from anywhere.",
    image: "https://images.ctfassets.net/m3x6aw9x53qp/2MH1knjEQo4yvOhLx7Lh6/065ed794a92347be3b6df4d8c5995cbf/CP_Plus_Baby_Camera.webp",
    mediaType: "image",
    redirectUrl: "https://www.flipkart.com/cp-plus-cp-e35a-3mp-wi-fi-pt-360-view-2-way-talk-motion-alert-security-camera/p/itmc4a2169d1659c?pid=HSAGJT9QGHKH9U4S&lid=LSTHSAGJT9QGHKH9U4SPM8AL4",
    // imageClassName: "w-auto h-40 xl:h-48 absolute top-2",
    imageClassName: "w-auto h-48 xl:h-52 ",
    cardPosition: 'left',
    cardOffsetY: -60,
    brand: "/cp-plus-logo.webp",
    // brandClass: "h-auto w-12 sm:w-16 invert brightness-0",
    brandClass: "h-auto w-12 sm:w-16 invert brightness-0 translate-y-2 lg:translate-y-2.5",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Baby Camera",
    featuresWithIcons: [
      { text: "3MP Full HD Video Quality", icon: Monitor },
      { text: "Infrared Night Vision up to 10m", icon: Moon },
      { text: "Two-Way Audio Communication", icon: Volume2 },
      { text: "Motion Detection & Auto Tracking", icon: Radar },
      { text: "microSD Support up to 128GB", icon: HardDrive },
      { text: "H.264/H.265 Video Compression", icon: Film },
      { text: "360° Pan & 85° Tilt View", icon: Rotate3D  },
      { text: "2.4GHz Wi-Fi, Easy Setup", icon: Wifi },
      { text: "Works with Alexa & Google Assistant", icon: Bot },
      { text: "2-Year Warranty, Indoor Use Design", icon: ShieldCheck },
    ],
    hasLightBeam: true,
    beamAngle: 175, 
    beamLength: 900,
    beamWidth: 60,
    beamColor: '#ffffff', 
    beamSpread: 800,
    beamOpacity: 0.1,
    beamGlowIntensity: 2,
    buttonText: "Buy Now",
    hasMagnifier: true,
    magnifierZoom: 0.9,
    magnifierRadius: 80,
    magnifierImage: "/magnify/cp-baby-cam.webp",
    magnifierImageWidth: 700,
    magnifierImageHeight: 700,
    magnifierFocusX: 51,
    magnifierFocusY: 48,
  },
  {
    id: "4",
    x: 79.8,
    y: 47,
    title: "Smart Switch",
    description: "This smart switch module transforms your existing switches into smart ones, enabling remote control and automation without altering your current setup. Its seamless integration with voice assistants and mobile apps offers enhanced convenience and energy efficiency.",
    image: "https://images.ctfassets.net/m3x6aw9x53qp/5qCmGcwpkOkAZUCo5Et0o3/3a2790762ed38768c5fd7ae953aecaa0/Wirpo_Smart_Switch.webp",
    mediaType: "image",
    redirectUrl: "https://www.flipkart.com/wipro-wi-fi-smart-plug-universal-socket-white/p/itmbc6599da0cff8?pid=SSWFYKYBJZYFNSBN&lid=LSTSSWFYKYBJZYFNSBNVKOBV2&marketplace=FLIPKART&q=smart+plug+&store=igc%2Fsnr&spotlightTagId=default_FkPickId_igc%2Fsnr&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=19bb8153-7666-4e44-9507-e97dca242227.SSWFYKYBJZYFNSBN.SEARCH&ppt=sp&ppn=sp&ssid=jsplfc15800000001747997833834&qH=e17aa0db40d8c4ed",
    // imageClassName: "w-auto h-50 xl:h-56 absolute -top-6",
    imageClassName: "w-auto h-64 xl:h-72 -translate-y-2",
    cardPosition: 'left',
    cardOffsetY: -20,
    brand: "/wipro-logo.webp",
    // brandClass: "h-auto w-7 ml-3 sm:ml-5 invert brightness-0",
    brandClass: "h-auto w-8 lg:w-10 invert brightness-0 absolute right-4 -translate-y-1",
    brandLogoWidth: 200,
    brandLogoHeight: 48,
    productName: "Smart Switch",
    featuresWithIcons: [
      { text: "Mobile app control", icon: Smartphone },
      { text: "Control up to 4 switches", icon: SlidersHorizontal },
      { text: "Manual override support", icon: Hand },
      { text: "Compact retrofit design", icon: Layers },
      { text: "Energy-efficient operation", icon: Leaf },
      { text: "No hub required", icon: Zap  },
      { text: "Wi-Fi connectivity (2.4GHz)", icon: Wifi },
      { text: "Voice assistant compatibility (Alexa, Google Assistant)", icon: Mic },
    ],
    buttonText: "Buy Now",
    hasMagnifier: true,
    magnifierZoom: 0.9,
    magnifierRadius: 70,
    magnifierImage: "/magnify/smart-switch.webp",
    magnifierImageWidth: 600,
    magnifierImageHeight: 600,
    magnifierFocusX: 50,
    magnifierFocusY: 49,
  },
];
